version: '3.8'

services:
  react-app:
    image: node:latest
    container_name: front-end_flow
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "5173:5173"

  web-api:
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    container_name: back-end_flow
    working_dir: /app
    command: sh -c "dotnet restore && dotnet watch run"
    ports:
      - "5105:5105"
    depends_on:
      - mysql-db
      - mongo-db

  mysql-db:
    image: mysql:latest
    container_name: mysql_flow
    environment:
      MYSQL_ROOT_PASSWORD: xpvista7810
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: lendacerda
      MYSQL_PASSWORD: xpvista7810
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  mongo-db:
    image: mongo:latest
    container_name: mongo_flow
    environment:
      MONGO_INITDB_ROOT_USERNAME: lendacerda
      MONGO_INITDB_ROOT_PASSWORD: xpvista7810
      MONGO_INITDB_DATABASE: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
