version: '3.8'

services:
  react-app:
    image: node:latest
    container_name: front-end
    working_dir: /app
    command: sh -c "npm install && npm start"
    resources:
      limits:
        memory: 1GB
    ports:
      - "3000:3000" #PLACEHOLDER

  web-api:
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    container_name: back-end
    working_dir: /app
    command: sh -c "dotnet restore && dotnet watch run"
    resources:
      limits:
        memory: 1GB
    ports:
      - "5000:5000" #PLACEHOLDER
    depends_on:
      - mysql-db
      - mongo-db

  mysql-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: xpvista7810
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: lendacerda
      MYSQL_PASSWORD: xpvista7810
    resources:
      limits:
        memory: 1GB
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  mongo-db:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: lendacerda
      MONGO_INITDB_ROOT_PASSWORD: xpvista7810
      MONGO_INITDB_DATABASE: mongo_db
    resources:
      limits:
        memory: 1GB
    ports:
      - "27017:27017" #PLACEHOLDER
    volumes:
      - ./mongo-data:/data/db
